id = "imp"
name = "Imp"
version = "0.0.1"
schema_version = 1
authors = ["Enea Giger <enea.giger@tuta.io>"]
description = "Language support for the language Imp made for my matura project."
repository = "https://github.com/enmiligi/zed-imp"

[grammars.imp]
repository = "https://github.com/enmiligi/tree-sitter-imp"
rev = "0fbbb44e3414001f17b96c0b77d205ec0b1aecfb"
