name = "Imp"
grammar = "imp"
path_suffixes = ["imp"]
autoclose_before = ";,])"
line_comments = ["# "]

brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "stringLiteral",
        "charLiteral",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "stringLiteral",
        "charLiteral",
    ] },
]
